### ISSUE TITLE
Male Koala Event Detector SaveIntermediateCsvFiles fails when set to WhenEventsDetected

### ISSUE THREAD

**Issue by Allcharles** [QutEcoacoustics/audio-analysis#245]
## Describe the bug

AP fails when running audio2csv using a modified Towsey.KoalaMale.yml file with following changes:

- `SaveIntermediateWavFiles: WhenEventsDetected`
- `SaveIntermediateCsvFiles: WhenEventsDetected`
- `SaveSonogramImages: WhenEventsDetected`

Program throws an Unhandled exception because `The value "WhenEventsDetected" is not a valid YML Boolean`

## Expected behavior 

Should generate the sonograms, csv's, and wav files after analysis is complete.

## Diagnostics
- Operating System: Windows 10
- AP: version 19.6.1.1
- Log: [log.txt](https://github.com/QutEcoacoustics/audio-analysis/files/3359340/log.txt)
- Config: [Towsey.KoalaMale.AP_DESKTOP_TEMP.1562243830862.zip](https://github.com/QutEcoacoustics/audio-analysis/files/3359346/Towsey.KoalaMale.AP_DESKTOP_TEMP.1562243830862.zip)

- Command: 
``` bash
AnalysisPrograms.exe audio2csv audioFile.wav Towsey.KoalaMale.AP_DESKTOP_TEMP.1562243830862.yml outputFolder --mix-down-to-mono=false --parallel
```

**Comment by atruskie** [comment]
So `SaveIntermediateCsvFiles` only accepts a boolean (`true`/`false`) unlike `SaveSonogramImages` and `SaveIntermediateWavFiles`. That's because there is little to no utility in saving intermediate CSV files so we didn't enhance that feature when we improved the other two options.

This is not a bug.

Do you want this behaviour augmented, or changed? Maybe documentation on the accepted values for `SaveIntermediateWavFiles` would suffice?

**Comment by Allcharles** [comment]
Updating
```
# Available options (case-sensitive): [False/Never | True/Always | WhenEventsDetected]
SaveIntermediateWavFiles: Never
SaveIntermediateCsvFiles: false
```
to
```
# Available options (case-sensitive): [False/Never | True/Always | WhenEventsDetected]
SaveIntermediateWavFiles: Never
# Available options (case-sensitive): [False/Never | True/Always]
SaveIntermediateCsvFiles: false
```
Should be fine
